#ifndef MIDI2CV_DRIVERS_SPI_MODE_H
#define MIDI2CV_DRIVERS_SPI_MODE_H

#include <stm32f3xx_hal.h>

enum SPIMode {
  SPI_MODE_UNINITIALIZED,
  SPI_MODE_DISPLAY,
  SPI_MODE_DAC0,
  SPI_MODE_DAC1,
  SPI_MODE_USB
};

void InitSPI(SPIMode mode);

#endif
